<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <RootNamespace>BoxForge.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../BoxForge.Core/BoxForge.Core.csproj" />
  </ItemGroup>

</Project>
